
spring:
    datasource:
        name: test
        url: jdbc:mysql://yxyezd.picp.net:3309/online?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: admin
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    jpa:
        database : MYSQL
        show-sql : true
        hibernate:
            ddl-auto : update
            naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
            dialect : org.hibernate.dialect.MySQL5Dialect

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.casaba.dao.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql